export const BET_OPEN = "BET_OPEN";
export const BET_CLOSE = "BET_CLOSE";
export const FETCH_BET = "FETCH_BET";
export const DISCONNECT = "DISCONNECT";
export const FETCH_INFO = "FETCH_INFO";
export const RECEIVE_INFO = "RECEIVE_INFO";
export const CHECK_BET = "CHECK_BET";
export const RECEIVE_BET = "RECEIVE_BET";
export const PAIR_UPDATED = "PAIR_UPDATED";
export const UPDATED_INFO = "UPDATED_INFO";

export const TRANSACTION = "TRANSACTION";
export const TOPUP = "TOPUP";
export const TWODHISTORY = "TWODHISTORY";
export const THREEDHISTORY = "THREEDHISTORY";



export const FETCH_ADMIN = "FETCH_ADMIN";
export const FETCH_SERVER = "FETCH_SERVER";
export const RECEIVE_ADMIN = "RECEIVE_ADMIN";
export const UPDATED_ADMIN = "UPDATED_ADMIN";


export const PAUSED_SERVER = "PAUSED_SERVER";
export const RESUME_SERVER = "RESUME_SERVER";
export const ADDWINNER_NUMBER = "ADDWINNER_NUMBER";
export const CHECK = "CHECK";
export const WINNERS = "WINNERS";
export const PASSWINNER_SERVER = "PASSWINNER_SERVER";

export const MESSAGE = "MESSAGE";
export const CONNECT_SERVICE = "CONNECT_SERVICE";
export const REPLY = "REPLY";
export const DISCONNECT_SERVICE = "DISCONNECT_SERVICE";
export const SERVICE_CONNECTED = "SERVICE_CONNECTED";
export const SERVICE_DISCONNECTED = "SERVICE_DISCONNECTED";
export const MESSAGE_TO_ROOM = "MESSAGE_TO_ROOM";

export const JOIN_SERVICE = "JOIN_SERVICE";
export const JOINED_SERVICE = "JOINED_SERVICE";
export const DISCONNECTED_SERVICE = "DISCONNECTED_SERVICE";